New pages for profile, new components and styles
OpenStackweb/osf-website pull request #254
Opened 2022-04-14 14:38 UTC by tomrndom

WIP

ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2877727

Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>

2022-04-21 00:43 UTC, smarcet commented on src/actions/user-actions.js
>        dispatch(stopLoading());
add a visual feedback for a successful operation 
a modal message would do the trick

2022-04-21 00:45 UTC, smarcet commented on src/components/ProfileManagementComponent.js
> +      Swal.fire("Validation error", msg, "warning");
here you could use.a return and remove the else branch

2022-04-21 01:05 UTC, smarcet commented on src/components/Affiliations.js
> -                                        <button data-id={a.id} onClick={this.onHandleDelete}>Delete</button>
on handleDelete use ev.currentTarget instead of ev.target

2022-04-21 01:06 UTC, smarcet commented on src/components/Affiliations.js
> +                                        <button data-id={a.id} onClick={this.onHandleEdit}>
on onHandleEdit use ev.currentTarget instead of ev.target

2022-04-21 01:06 UTC, smarcet requested changes
@tomrndom plese review comments

2022-04-25 20:45 UTC, iamweswilson commented
Update this text to the following: 

"Speakers agree that OpenInfra Foundation may record and publish any talks presented during the OpenInfra Summit. If you submit a proposal on behalf of a speaker, you represent to OpenInfra Foundation that you have the authority to submit the proposal on the speaker's behalf and agree to the recording and publication of their presentation."

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiYjliY2NhZjctZDY4NS00M2ZmLTg5YWUtOGE5NGY4NGI0NDM1IiwiZGVwbG95X2lkIjoiNjI2NmViODU2NjZiNjMwMDA5MDU0YWY4IiwiaWQiOiIxZDU0ZWU4NC1hYjM3LTQ2ZjAtOWZkMC0zYjE5NTg4YTUzOWMifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /a/profile/speaker
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1440 x 725 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-254--openinfra-dev.netlify.app%2Fa%2Fprofile%2Fspeaker&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1440x725&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-254--openinfra-dev.netlify.app/a/profile/speaker) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6266eb85666b630009054af8&commentID=6267084dbc8c460b7418425a&resolution=resolved)

2022-04-25 20:51 UTC, iamweswilson commented
Can we make sure the pics shown are circles? I think this is happening because this pic width is not 200px

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiYjliY2NhZjctZDY4NS00M2ZmLTg5YWUtOGE5NGY4NGI0NDM1IiwiZGVwbG95X2lkIjoiNjI2NmViODU2NjZiNjMwMDA5MDU0YWY4IiwiaWQiOiJkYTJlNzI1My04YWJiLTQ1MzEtYjYxYS1mNDg1NzNiZDUxMzQifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /a/profile/speaker
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1440 x 725 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-254--openinfra-dev.netlify.app%2Fa%2Fprofile%2Fspeaker&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1440x725&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-254--openinfra-dev.netlify.app/a/profile/speaker) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6266eb85666b630009054af8&commentID=626709c89197160d43acd805&resolution=resolved)

2022-04-25 20:55 UTC, iamweswilson commented
'&' converts to unicode when saved, can we keep what's typed?

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiYjliY2NhZjctZDY4NS00M2ZmLTg5YWUtOGE5NGY4NGI0NDM1IiwiZGVwbG95X2lkIjoiNjI2NmViODU2NjZiNjMwMDA5MDU0YWY4IiwiaWQiOiI0ZGE1NDRhNi1mNTMwLTQ4YzQtYWMzMi04NjZjZTdmYWJlNjkifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /a/profile/speaker
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1440 x 725 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-254--openinfra-dev.netlify.app%2Fa%2Fprofile%2Fspeaker&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1440x725&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-254--openinfra-dev.netlify.app/a/profile/speaker) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6266eb85666b630009054af8&commentID=62670ac693799f08b5db09c1&resolution=resolved)

2022-04-25 23:01 UTC, smarcet commented
> I notice we're using a different data source for https://deploy-preview-254--openinfra-dev.netlify.app/a/profile/speaker and https://deploy-preview-254--openinfra-dev.netlify.app/a/profile. Is it possible to consolidate those or have we kept it this way to allow speakers to change the image they use for their sessions?
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-254--openinfra-dev.netlify.app/a/profile/speaker) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6266eb85666b630009054af8&commentID=62670bd6f02f5405ce33ad5b&resolution=resolved)

@iamweswilson that is done on that way to keep data for speaker separated from the member its has been on that way since forever and change it will entail a massive change 
regards

2022-04-25 23:02 UTC, smarcet commented
> Can we only show this button when nominations are open? Doesn't look like we're currently showing it on https://www.openstack.org/profile/election
> 
> ![screenshot](https://camo.githubusercontent.com/aa834aaabdd5ce0d23a836cb05e0c512330a02a7bb18a8492e3a1bb101bf5e2c/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f69596a6c6959324e685a6a63745a4459344e5330304d325a6d4c546735595755744f4745354e4759344e4749304e444d31496977695a4756776247393558326c6b496a6f694e6a49324e6d56694f4455324e6a5a694e6a4d774d4441354d4455305957593449697769615751694f694a6a4d7a646d4e5445315a43316d4e544e6a4c54517a4e4459744f544e684e6931684d325a6b5a546b304f5749334d44636966513d3d)
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-254--openinfra-dev.netlify.app/a/profile/elections) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6266eb85666b630009054af8&commentID=62670b57301d3c049a20a027&resolution=resolved)

@iamweswilson this is pointing to devbranch.openstack.org 
could you check there ?
regards

2022-04-25 23:15 UTC, smarcet approved these changes
LGTM

2022-04-26 05:00 UTC, iamweswilson commented
I don't see the button on devbranch either ![image](https://user-images.githubusercontent.com/214968/165225023-3a4a7840-7c93-4584-96f5-08874b49c486.png)

2022-04-27 04:31 UTC, merged